### ISSUE TITLE
Intellihide flashes

### ISSUE THREAD

**Issue by Kingzsf** [tuxor1337/hidetopbar#397] opened 2023-01-29 05:44 UTC
Dear author, I have encountered a problem that when dash to dock and hide top bar are installed at the same time, the mouse will flash after the program is opened to the maximum (both extensions will flash). 1. At the beginning, I thought it was due to the problem of the notebook graphics card driver. Later, after checking, I suspected it was due to the problem of smart hide settings. Finally, after trying to disable the hide top bar, the dash to dock is normal, so the problem still exists in this extension and will affect the dash to dock.
See the demo video below for details.
https://user-images.githubusercontent.com/102367425/215307454-06573c5f-f8f5-495f-9bc2-c1190674484b.mp4

It has always supported your extension. Please correct it. The computer configuration is also attached.
```shell
[zhousf@fedora ~]$ sudo inxi -Fzx
System:
  Kernel: 6.1.7-200.fc37.x86_64 arch: x86_64 bits: 64 compiler: gcc v: 2.38-25.fc37
    Console: pty pts/0 Distro: Fedora release 37 (Thirty Seven)
Machine:
  Type: Laptop System: Dell product: XPS 13 9350 v: N/A serial: <filter>
  Mobo: Dell model: 0JXC1H v: X00 serial: <filter> UEFI: Dell v: 1.13.0 date: 02/10/2020
Battery:
  ID-1: BAT0 charge: 52.7 Wh (100.0%) condition: 52.7/52.7 Wh (100.0%) volts: 8.5 min: 7.6
    model: SMP DELL RWT1R43 status: full
CPU:
  Info: dual core model: Intel Core i7-6560U bits: 64 type: MT MCP arch: Skylake rev: 3
    cache: L1: 128 KiB L2: 512 KiB L3: 4 MiB
  Speed (MHz): avg: 2679 high: 3165 min/max: 400/3200 cores: 1: 3154 2: 3165 3: 2200
    4: 2200 bogomips: 17599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Iris Graphics 540 vendor: Dell driver: i915 v: kernel arch: Gen-9
    bus-ID: 00:02.0
  Device-2: Microdia Integrated Webcam HD type: USB driver: uvcvideo bus-ID: 1-5:3
  Display: server: X.org v: 1.20.14 with: Xwayland v: 22.1.7 driver: gpu: i915
    note: X driver n/a tty: 92x27 resolution: 1920x1080
  API: OpenGL Message: GL data unavailable in console for root.
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Dell driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3
  Sound API: ALSA v: k6.1.7-200.fc37.x86_64 running: yes
  Sound Server-1: PulseAudio v: 16.1 running: no
  Sound Server-2: PipeWire v: 0.3.64 running: yes
Network:
  Device-1: Broadcom BCM4350 802.11ac Wireless Network Adapter vendor: Dell
    driver: brcmfmac v: kernel bus-ID: 3a:00.0
  IF: wlp58s0 state: up mac: <filter>
Bluetooth:
  Device-1: Broadcom BCM2045A0 type: USB driver: btusb v: 0.8 bus-ID: 1-3:2
  Report: rfkill ID: hci0 rfk-id: 0 state: up address: see --recommends
Drives:
  Local Storage: total: 238.47 GiB used: 13.32 GiB (5.6%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: PM951 NVMe 256GB size: 238.47 GiB
    temp: 39.9 C
Partition:
  ID-1: / size: 236.89 GiB used: 13.04 GiB (5.5%) fs: btrfs dev: /dev/nvme0n1p3
  ID-2: /boot size: 973.4 MiB used: 271.9 MiB (27.9%) fs: ext4 dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 598.8 MiB used: 17.4 MiB (2.9%) fs: vfat dev: /dev/nvme0n1p1
  ID-4: /home size: 236.89 GiB used: 13.04 GiB (5.5%) fs: btrfs dev: /dev/nvme0n1p3
Swap:
  ID-1: swap-1 type: zram size: 7.61 GiB used: 21.2 MiB (0.3%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 52.0 C pch: 52.0 C mobo: 42.0 C sodimm: SODIMM C
  Fan Speeds (RPM): cpu: 0
Info:
  Processes: 301 Uptime: 42m Memory: 7.61 GiB used: 3.02 GiB (39.6%) Init: systemd
  target: graphical (5) Compilers: gcc: 12.2.1 Packages: 2 note: see --rpm Shell: Bash
  v: 5.2.15 inxi: 3.3.24
```

**Comment by Kingzsf** [comment] 2023-01-29 05:45
https://user-images.githubusercontent.com/102367425/215307511-992e4ba8-682a-4ec1-b809-d35714c067b8.mp4

**Comment by tuxor1337** [comment] 2023-01-31 16:03
Closing as duplicate of #372

**Closed by tuxor1337** 2023-01-31 16:03 UTC
