### ISSUE TITLE
Update to support Gnome 43

### ISSUE THREAD

**Issue by marshallishere** [tuxor1337/hidetopbar#388] opened 2022-09-25 13:17 UTC
The title says everything.

**Comment by tuxor1337** [comment] 2022-09-25 15:57
If you or anyone else has the chance to test the extension under Gnome 43, please report back about your experience. Maybe we can just add support for 43 without any modifications.

**Comment by marshallishere** [comment] 2022-09-25 22:20
Tested on a Fedora Silverblue 37 Beta VM with the Extension Manager flatpak, seems to work just fine. No problems at all! If you want me to make some specific test I'm here.

**Comment by tuxor1337** [comment] 2022-09-26 06:10
Great, thanks for your feedback!

Okay, I will add 43 to the list of supported versions, if it's working for you. If somebody stumbles upon an incompatibility with a particular configuration, they will report it at some point and we can look into it again.

**Comment by marshallishere** [comment] 2022-09-26 11:08
Great! Thank you for the quick response.

**Comment by coldtobi** [comment] 2022-10-01 09:48
I can confirm, that 109 works with Gnome 43.

**Comment by behenate** [comment] 2022-11-14 13:41
I'm on Gnome 43 (Wayland) and in some apps eq. IntelliJ when trying to reveal the top bar by hovering on top of the screen it starts flickering. Most of other apps I've tried work fine though.

**Comment by BrazenFox5** [comment] 2022-11-16 16:52
On Wayland 43.0 with Fedora 37, it's working here.

**Comment by tuxor1337** [comment] 2022-11-16 18:03
@behenate I think the flickering thing is a longstanding issue: https://github.com/tuxor1337/hidetopbar/issues/372 Unfortunately, it's most probably an upstream bug.

Since everything is working fine I'm closing this as solved.

**Closed by tuxor1337** 2022-11-16 18:03 UTC
Labels: compatibility
