### ISSUE TITLE
GNOME 41: Top panel overlaps notifications

### ISSUE THREAD

**Issue by mi16087** [tuxor1337/hidetopbar#337] opened 2022-01-26 16:43 UTC
Top panel overlaps notifications:
![Screenshot from 2022-01-26 17-42-34](https://user-images.githubusercontent.com/44554049/151207558-2083353e-b819-4ac0-a6ca-58389493ad9d.png)
Expected behavior:
![Screenshot from 2022-01-26 17-48-02](https://user-images.githubusercontent.com/44554049/151208277-c3e34519-ad5f-4d54-9404-b6788f289b67.png)
I'm on Endeavour OS (Arch based distro) with gnome 41.
These are the settings I'm using:
![Screenshot from 2022-01-26 17-43-21](https://user-images.githubusercontent.com/44554049/151207854-dafcbeda-9663-4e6d-b64b-fabb996cbd0c.png)

**Comment by tuxor1337** [comment] 2022-01-26 16:49
I can't reproduce this on GNOME 40 (Fedora 34), and can't test it on GNOME 41 currently.

Do you have any other GNOME extensions activated in parallel? Do you use any kind of GNOME theming?

**Comment by tuxor1337** [comment] 2022-01-26 16:51
By the way, as a workaround, you can use the Panel OSD extension to change the location of the notifications, as mentioned in #275.

**Comment by mi16087** [comment] 2022-01-26 16:56
These're all the extensions active right now beside Hide top bar:
  AppIndicator and KStatusNotifierItem Support 
  Blur my Shell 
  Caffeine
  Dash to Dock 
  Desktop Icons NG (DING) 
  GSConnect 
  Notification Timeout
  Pamac Updates Indicator
  Removable Drive Menu 
  Sound Input & Output Device Chooser 
  Status Area Horizontal Spacing 
  Todo.txt 
  User Themes
  Weeks Start on Monday Again... 

And the theme im useing for shell is WhiteSur

**Comment by tuxor1337** [comment] 2022-01-26 19:34
Okay, can you reproduce this with several or all of the extensions disabled and the default theme?

**Comment by mi16087** [comment] 2022-01-26 21:48
Yes, it's still there
![Screenshot from 2022-01-26 22-47-24](https://user-images.githubusercontent.com/44554049/151252553-4c20f7e2-0323-43cc-8069-52e972eb7c0a.png)

**Comment by Petapton** [comment] 2022-02-14 20:38
Hello, I also noticed that with DING it also overlaps desktop icons.
![](https://user-images.githubusercontent.com/14984292/153942538-b1fb5a9f-4733-4e07-88f9-fd12bfeaf3b0.png)
I think the two issues have something to do with PanelBox (in panelVisibilityManager.js) reporting height 0, but take it as a guess.

**Comment by tuxor1337** [comment] 2022-08-22 20:29
@Petapton Your point is unrelated to this issue and should already be fixed by #322.

@mi16087 Since I'm on GNOME 42 now and still can't reproduce this issue, I'm closing this, sorry.

**Closed by tuxor1337** 2022-08-22 20:29 UTC
Labels: compatibility
