### ISSUE TITLE
With auto-hide bar enabled, in maximized windows with no system default title bar, bar would show but instantaneously hide again, cant show effectively

### ISSUE THREAD

**Issue by eyrent** [tuxor1337/hidetopbar#383] opened 2022-09-04 21:35 UTC
I noticed that whenever I have a window which has got a custom or integrated titlebar, gnome bar would hide as usual but would fail to show when mouse was pushed to the top (revealing behavior). You can see the sliding animation but then the bar disappears. It reappears brifly when mouse leaves the areas the sliding animation is presented. If the window has 'normal' title bar this is not the case, and everything works as expected. I'm attacking pictures of what a 'normal' title bar and a 'custom' one means. Thanks
NORMAL WINDOW TITLE BAR
![image](https://user-images.githubusercontent.com/46402074/188334449-1fc20cdc-c699-4e84-8dcc-ec20e60514bf.png)
CUSTOM WINDOW TITLE BAR
![image](https://user-images.githubusercontent.com/46402074/188334470-8fad9a0f-1295-4786-b771-483911202696.png)

**Comment by tuxor1337** [comment] 2022-09-05 05:38
Duplicate of #372

**Closed by tuxor1337** 2022-09-05 05:38 UTC
