### ISSUE TITLE
extension stops working and top bar remains visible after monitor turned off and on

### ISSUE THREAD

**Issue by jamdox** [tuxor1337/hidetopbar#379] opened 2022-08-29 03:13 UTC
error in journalctl listed as originating with gnome-shell:
`JS ERROR: TypeError: this._intellihide is undefined
                                            _updateStaticBox@/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:320:9
                                            onComplete@/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:149:26
                                            _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:153:13
                                            _easeActor/<@resource:///org/gnome/shell/ui/environment.js:240:64
`
Error listed in gnome extensions app: "Main.layoutManager.primaryMonitor is null"

It looks like it can't find the monitor after it's turned back on...

**Comment by tuxor1337** [comment] 2022-08-29 17:24
Closing as duplicate of #360

**Closed by tuxor1337** 2022-08-29 17:24 UTC
