### ISSUE TITLE
TopBar disapears after  unlock screen in ubuntu 21.04 

### ISSUE THREAD

**Issue by manisabri** [tuxor1337/hidetopbar#387] opened 2022-09-15 16:06 UTC
TopBar disapears after  unlock screen in ubuntu 21.04

**Comment by tuxor1337** [comment] 2022-09-16 19:01
Closing as duplicate of #365

**Closed by tuxor1337** 2022-09-16 19:01 UTC

**Comment by tuxor1337** [comment] 2022-09-16 20:33
So, it's actually a duplicate of #319 I guess.
