### ISSUE TITLE
Top bar stuck open after monitor turns off and on again.

### ISSUE THREAD

**Issue by MadMinstrel** [tuxor1337/hidetopbar#374] opened 2022-07-22 07:19 UTC
The top bar gets stuck open after the monitor gets turned off by Gnome's automatic screen blank power setting. If I open the Extensions app, there's an error message that says "Main.layoutManager.primaryMonitor is null".

Gnome version is 42.3 running on X11, on Manjaro (Gnome flavor) with Nvidia. Display is an LG TV, connected over HDMI.

**Comment by tuxor1337** [comment] 2022-07-24 18:20
Possibly a duplicate of #182 and/or #154

**Comment by tuxor1337** [comment] 2022-08-29 17:26
Closing as duplicate of #360

**Closed by tuxor1337** 2022-08-29 17:26 UTC
Labels: multi-monitor
