### ISSUE TITLE
Top bar comes back after disconnecting/reconnecting my monitor

### ISSUE THREAD

**Issue by davehensley** [tuxor1337/hidetopbar#182] opened 2019-07-23 02:47 UTC
Thank you for this useful extension.

I'm using a single monitor (actually a TV) that can switch between several input sources. If I switch to one of the other inputs and then switch back to my PC, the top bar becomes unhidden. In order to hide it again, I need to mouseover the top bar and then drag the mouse away.

I've tested both the [debian package](https://packages.debian.org/buster/gnome-shell-extension-autohidetopbar) (20180908-2) and the current master branch. I am using Debian Buster 10.0 amd64 with gnome-shell 3.30.2-9.

This might possibly be related to https://github.com/mlutfy/hidetopbar/issues/154.

**Comment by tuxor1337** [comment] 2022-08-29 17:25
Closing as duplicate of #360

**Closed** 2022-12-10 08:33 UTC
Labels: duplicate, multi-monitor
