### ISSUE TITLE
Ubuntu 22.04 LTS Search bar issue 

### ISSUE THREAD

**Issue by nasim0x1** [tuxor1337/hidetopbar#375] opened 2022-07-30 09:38 UTC
![Screenshot from 2022-07-30 15-30-06](https://user-images.githubusercontent.com/68021246/181904588-7d0d5070-6495-4cd3-b511-a0899bc4a37c.png)
i am getting searchbar like this . hope it will fix soon .

**Comment by tuxor1337** [comment] 2022-07-30 09:56
Closing as duplicate of #321

**Closed by tuxor1337** 2022-07-30 09:56 UTC
